# Generated by Django 4.1.2 on 2022-11-29 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_teammember_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPageConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=64)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.team')),
            ],
        ),
        migrations.CreateModel(
            name='StatusPageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.team')),
            ],
        ),
    ]
