# Generated by Django 4.1.2 on 2022-11-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuspage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuspageconfiguration',
            name='path',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
