# Generated by Django 4.1.2 on 2022-12-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuspage', '0002_alter_statuspageconfiguration_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuspageconfiguration',
            name='path',
            field=models.CharField(default=None, max_length=64, null=True, unique=True),
        ),
    ]
