# Generated by Django 4.1.1 on 2022-10-31 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholdconfig',
            name='threshold_pct',
            field=models.IntegerField(blank=True, default=100, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
