# Generated by Django 4.1.1 on 2022-10-31 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_thresholdconfig_threshold_pct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThresholdConfig',
        ),
    ]
