# Generated by Django 4.1.1 on 2022-10-04 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimonitorresult',
            name='log_error',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apimonitorrawbody',
            name='monitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_body', to='apimonitor.apimonitor'),
        ),
    ]
