# Generated by Django 4.1.1 on 2022-10-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0002_apimonitorresult_log_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimonitorresult',
            name='status_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
