# Generated by Django 4.1.1 on 2022-10-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0003_apimonitorresult_status_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apimonitorresult',
            name='date',
        ),
        migrations.RemoveField(
            model_name='apimonitorresult',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='apimonitorresult',
            name='minute',
        ),
        migrations.AddIndex(
            model_name='apimonitorresult',
            index=models.Index(fields=['monitor', 'execution_time'], name='result_time_index'),
        ),
        migrations.AddIndex(
            model_name='apimonitorresult',
            index=models.Index(fields=['monitor', 'success'], name='result_success_index'),
        ),
    ]
