# Generated by Django 4.1.1 on 2022-10-17 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apimonitor', '0004_remove_apimonitorresult_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimonitor',
            name='assertion_value',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apimonitor',
            name='assetion_type',
            field=models.CharField(choices=[('DISABLED', 'Disabled'), ('TEXT', 'Text'), ('JSON', 'JSON')], default='DISABLED', max_length=16),
        ),
        migrations.AddField(
            model_name='apimonitor',
            name='previous_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apimonitor.apimonitor'),
        ),
        migrations.CreateModel(
            name='AlertsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_slack_active', models.BooleanField(default=False)),
                ('slack_token', models.CharField(blank=True, default='', max_length=256)),
                ('slack_channel_id', models.CharField(blank=True, default='', max_length=256)),
                ('is_discord_active', models.BooleanField(default=False)),
                ('discord_bot_token', models.CharField(blank=True, default='', max_length=256)),
                ('discord_guild_id', models.CharField(blank=True, default='', max_length=256)),
                ('discord_channel_id', models.CharField(blank=True, default='', max_length=256)),
                ('is_pagerduty_active', models.BooleanField(default=False)),
                ('pagerduty_api_key', models.CharField(blank=True, default='', max_length=256)),
                ('pagerduty_default_from_email', models.CharField(blank=True, default='', max_length=256)),
                ('is_email_active', models.BooleanField(default=False)),
                ('email_host', models.CharField(blank=True, default='', max_length=1024)),
                ('email_port', models.IntegerField(blank=True, null=True)),
                ('email_username', models.CharField(blank=True, default='', max_length=1024)),
                ('email_password', models.CharField(blank=True, default='', max_length=1024)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
