# Generated by Django 4.1.1 on 2022-10-24 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0007_rename_assetion_type_apimonitor_assertion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assertionexcludekey',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclude_keys', to='apimonitor.apimonitor'),
        ),
    ]
