# Generated by Django 4.1.2 on 2022-10-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0008_alter_assertionexcludekey_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsconfiguration',
            name='email_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertsconfiguration',
            name='email_use_tls',
            field=models.BooleanField(default=False),
        ),
    ]
