# Generated by Django 4.1.1 on 2022-10-31 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0009_alertsconfiguration_email_use_ssl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsconfiguration',
            name='threshold_pct',
            field=models.IntegerField(blank=True, default=100, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='alertsconfiguration',
            name='time_window',
            field=models.CharField(choices=[('1H', '1 Hour'), ('2H', '2 Hour'), ('3H', '3 Hour'), ('6H', '6 Hour'), ('12H', '12 Hour'), ('24H', '24 Hour')], default='1H', max_length=16),
        ),
    ]
