# Generated by Django 4.1.2 on 2022-11-01 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0010_alertsconfiguration_threshold_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsconfiguration',
            name='pagerduty_service_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='apimonitor',
            name='last_notified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alertsconfiguration',
            name='threshold_pct',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
