# Generated by Django 4.1.2 on 2022-11-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0011_alertsconfiguration_pagerduty_service_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertsconfiguration',
            old_name='discord_guild_id',
            new_name='discord_webhook_url',
        ),
        migrations.RemoveField(
            model_name='alertsconfiguration',
            name='discord_bot_token',
        ),
        migrations.RemoveField(
            model_name='alertsconfiguration',
            name='discord_channel_id',
        ),
    ]
