# Generated by Django 4.1.2 on 2022-11-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0011_alertsconfiguration_pagerduty_service_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsconfiguration',
            name='email_address',
            field=models.EmailField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='alertsconfiguration',
            name='email_name',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
