# Generated by Django 4.1.2 on 2022-11-06 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0012_alertsconfiguration_email_address_and_more'),
        ('apimonitor', '0012_rename_discord_guild_id_alertsconfiguration_discord_webhook_url_and_more'),
    ]

    operations = [
    ]
