# Generated by Django 4.1.2 on 2022-11-15 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apimonitor", "0013_merge_20221106_1259"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertsconfiguration",
            name="utc",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-1200),
                    django.core.validators.MaxValueValidator(1400),
                ],
            ),
        ),
    ]
