# Generated by Django 4.1.2 on 2022-11-07 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('apimonitor', '0013_merge_20221106_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimonitor',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.team'),
        ),
    ]
