# Generated by Django 4.1.1 on 2022-11-15 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    db_alias = schema_editor.connection.alias
    
    Team = apps.get_model("login", "Team")
    users = User.objects.using(db_alias).all()
    team_mapping = {}
    for user in users:
        username = user.username.split('@')[0]
        team = Team.objects.create(name=username.title())
        team_mapping[user.id] = team
    
    APIMonitor = apps.get_model("apimonitor", "APIMonitor")
    api_monitor = APIMonitor.objects.using(db_alias).all()
    for monitor in api_monitor:
        monitor.team = team_mapping[monitor.user.id]
        monitor.save()
        
    AlertsConfiguration = apps.get_model("apimonitor", "AlertsConfiguration")
    configs = AlertsConfiguration.objects.using(db_alias).all()
    for config in configs:
        config.team = team_mapping[config.user.id]
        config.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0002_alter_team_description_alter_team_logo'),
        ('apimonitor', '0013_merge_20221106_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsconfiguration',
            name='team',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='login.team'),
        ),
        migrations.AddField(
            model_name='apimonitor',
            name='team',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='login.team'),
        ),
        migrations.RunPython(
            forwards_func,
        ),
        migrations.RemoveField(
            model_name='alertsconfiguration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='apimonitor',
            name='user',
        ),
    ]
