# Generated by Django 4.1.2 on 2022-11-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0014_apimonitor_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertsConfiguration',
        ),
    ]
