# Generated by Django 4.1.2 on 2022-11-07 14:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_teammember_unique_together'),
        ('apimonitor', '0015_AlertsConfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_slack_active', models.BooleanField(default=False)),
                ('slack_token', models.CharField(blank=True, default='', max_length=256)),
                ('slack_channel_id', models.CharField(blank=True, default='', max_length=256)),
                ('is_discord_active', models.BooleanField(default=False)),
                ('discord_webhook_url', models.CharField(blank=True, default='', max_length=256)),
                ('is_pagerduty_active', models.BooleanField(default=False)),
                ('pagerduty_api_key', models.CharField(blank=True, default='', max_length=256)),
                ('pagerduty_default_from_email', models.CharField(blank=True, default='', max_length=256)),
                ('pagerduty_service_id', models.CharField(blank=True, default='', max_length=64)),
                ('is_email_active', models.BooleanField(default=False)),
                ('email_name', models.CharField(blank=True, default='', max_length=1024)),
                ('email_address', models.EmailField(blank=True, max_length=1024)),
                ('email_host', models.CharField(blank=True, default='', max_length=1024)),
                ('email_port', models.IntegerField(blank=True, null=True)),
                ('email_username', models.CharField(blank=True, default='', max_length=1024)),
                ('email_password', models.CharField(blank=True, default='', max_length=1024)),
                ('email_use_tls', models.BooleanField(default=False)),
                ('email_use_ssl', models.BooleanField(default=False)),
                ('threshold_pct', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('time_window', models.CharField(choices=[('1H', '1 Hour'), ('2H', '2 Hour'), ('3H', '3 Hour'), ('6H', '6 Hour'), ('12H', '12 Hour'), ('24H', '24 Hour')], default='1H', max_length=16)),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.team')),
            ],
        ),
    ]
