# Generated by Django 4.1.2 on 2022-11-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0014_alertsconfiguration_utc'),
        ('apimonitor', '0015_alter_alertsconfiguration_team_alter_apimonitor_team'),
    ]

    operations = [
    ]
