# Generated by Django 4.1.2 on 2022-11-29 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statuspage', '0001_initial'),
        ('apimonitor', '0016_merge_20221116_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimonitor',
            name='status_page_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statuspage.statuspagecategory'),
        ),
    ]
