# Generated by Django 4.1.2 on 2022-11-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_teammember_unique_together'),
        ('apimonitor', '0016_AlertsConfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimonitor',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.team'),
        ),
    ]
