# Generated by Django 4.1.2 on 2022-12-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0017_apimonitor_status_page_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimonitor',
            name='assertion_type',
            field=models.CharField(choices=[('DISABLED', 'Disabled'), ('TEXT', 'Text'), ('JSON', 'JSON'), ('PARTIAL', 'Partial')], default='DISABLED', max_length=16),
        ),
    ]
