# Generated by Django 4.1.2 on 2022-11-08 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0017_alter_apimonitor_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apimonitor',
            name='user',
        ),
    ]
