# Generated by Django 4.1.2 on 2022-11-20 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_teammember_verified'),
        ('invite_team_members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inviteteammembertoken',
            name='team',
        ),
        migrations.RemoveField(
            model_name='inviteteammembertoken',
            name='user',
        ),
        migrations.AddField(
            model_name='inviteteammembertoken',
            name='team_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.teammember'),
            preserve_default=False,
        ),
    ]
