name: Test
on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Run test and coverage report
        run: |
          pip install -r requirements.txt
          python manage.py test